name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      build-and-push:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./src
        steps:
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GHCR_TOKEN}}

          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: "{{defaultContext}}:src"
              platforms: linux/amd64,linux/arm64
              push: true
              tags: ghcr.io/bruhtek/docker-certbot-dns-cloudflare:latest
